import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { TopNav } from "components/topNav";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "components/theme-provider";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={GeistSans.variable}>
        <body>
          <ThemeProvider attribute="class" defaultTheme="system">
            <TopNav />
            <main>{children}</main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
